// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"staff/internal/biz"
	"staff/internal/conf"
	"staff/internal/data"
	"staff/internal/server"
	"staff/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	staffRepo := data.NewStaffRepo(dataData, logger)
	staffUsecase := biz.NewStaffUsecase(staffRepo, logger)
	teamRepo := data.NewTeamRepo(dataData, logger)
	teamUsecase := biz.NewTeamUsecase(teamRepo, logger)
	teamStaffRepo := data.NewTeamStaffRepo(dataData, logger)
	teamStaffUsecase := biz.NewTeamStaffUsecase(teamStaffRepo, logger)
	staffService := service.NewStaffService(staffUsecase, teamUsecase, teamStaffUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, staffService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
