// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: staff/v1/staff.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建Staff请求接口参数
type CreateStaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"` // 手机号码
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`     // 员工姓名
}

func (x *CreateStaffRequest) Reset() {
	*x = CreateStaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStaffRequest) ProtoMessage() {}

func (x *CreateStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStaffRequest.ProtoReflect.Descriptor instead.
func (*CreateStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStaffRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateStaffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateStaffReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exec bool `protobuf:"varint,1,opt,name=exec,proto3" json:"exec,omitempty"` // 执行结果
}

func (x *CreateStaffReply) Reset() {
	*x = CreateStaffReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStaffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStaffReply) ProtoMessage() {}

func (x *CreateStaffReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStaffReply.ProtoReflect.Descriptor instead.
func (*CreateStaffReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStaffReply) GetExec() bool {
	if x != nil {
		return x.Exec
	}
	return false
}

type UpdateStaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateStaffRequest) Reset() {
	*x = UpdateStaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffRequest) ProtoMessage() {}

func (x *UpdateStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffRequest.ProtoReflect.Descriptor instead.
func (*UpdateStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStaffRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStaffRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpdateStaffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateStaffReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exec bool `protobuf:"varint,1,opt,name=exec,proto3" json:"exec,omitempty"`
}

func (x *UpdateStaffReply) Reset() {
	*x = UpdateStaffReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStaffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffReply) ProtoMessage() {}

func (x *UpdateStaffReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffReply.ProtoReflect.Descriptor instead.
func (*UpdateStaffReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStaffReply) GetExec() bool {
	if x != nil {
		return x.Exec
	}
	return false
}

type DeleteStaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteStaffRequest) Reset() {
	*x = DeleteStaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStaffRequest) ProtoMessage() {}

func (x *DeleteStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStaffRequest.ProtoReflect.Descriptor instead.
func (*DeleteStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteStaffRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteStaffReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exec bool `protobuf:"varint,1,opt,name=exec,proto3" json:"exec,omitempty"`
}

func (x *DeleteStaffReply) Reset() {
	*x = DeleteStaffReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStaffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStaffReply) ProtoMessage() {}

func (x *DeleteStaffReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStaffReply.ProtoReflect.Descriptor instead.
func (*DeleteStaffReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteStaffReply) GetExec() bool {
	if x != nil {
		return x.Exec
	}
	return false
}

type ReadStaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadStaffRequest) Reset() {
	*x = ReadStaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStaffRequest) ProtoMessage() {}

func (x *ReadStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStaffRequest.ProtoReflect.Descriptor instead.
func (*ReadStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{6}
}

func (x *ReadStaffRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadStaffReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staff *StaffReply `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
}

func (x *ReadStaffReply) Reset() {
	*x = ReadStaffReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadStaffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStaffReply) ProtoMessage() {}

func (x *ReadStaffReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStaffReply.ProtoReflect.Descriptor instead.
func (*ReadStaffReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{7}
}

func (x *ReadStaffReply) GetStaff() *StaffReply {
	if x != nil {
		return x.Staff
	}
	return nil
}

type RecoveryStaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RecoveryStaffRequest) Reset() {
	*x = RecoveryStaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoveryStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryStaffRequest) ProtoMessage() {}

func (x *RecoveryStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryStaffRequest.ProtoReflect.Descriptor instead.
func (*RecoveryStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{8}
}

func (x *RecoveryStaffRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RecoveryStaffReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exec bool `protobuf:"varint,1,opt,name=exec,proto3" json:"exec,omitempty"`
}

func (x *RecoveryStaffReply) Reset() {
	*x = RecoveryStaffReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoveryStaffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryStaffReply) ProtoMessage() {}

func (x *RecoveryStaffReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryStaffReply.ProtoReflect.Descriptor instead.
func (*RecoveryStaffReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{9}
}

func (x *RecoveryStaffReply) GetExec() bool {
	if x != nil {
		return x.Exec
	}
	return false
}

type ListStaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pn        int32  `protobuf:"varint,1,opt,name=pn,proto3" json:"pn,omitempty"`       // 选择页
	PSize     int32  `protobuf:"varint,2,opt,name=pSize,proto3" json:"pSize,omitempty"` // 选择页列表项数量
	Mobile    string `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	IsDeleted bool   `protobuf:"varint,5,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
}

func (x *ListStaffRequest) Reset() {
	*x = ListStaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffRequest) ProtoMessage() {}

func (x *ListStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffRequest.ProtoReflect.Descriptor instead.
func (*ListStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{10}
}

func (x *ListStaffRequest) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *ListStaffRequest) GetPSize() int32 {
	if x != nil {
		return x.PSize
	}
	return 0
}

func (x *ListStaffRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ListStaffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListStaffRequest) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ListStaffReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data  []*StaffReply `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListStaffReply) Reset() {
	*x = ListStaffReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStaffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffReply) ProtoMessage() {}

func (x *ListStaffReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffReply.ProtoReflect.Descriptor instead.
func (*ListStaffReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{11}
}

func (x *ListStaffReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListStaffReply) GetData() []*StaffReply {
	if x != nil {
		return x.Data
	}
	return nil
}

type StaffReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile    string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt string `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *StaffReply) Reset() {
	*x = StaffReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffReply) ProtoMessage() {}

func (x *StaffReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffReply.ProtoReflect.Descriptor instead.
func (*StaffReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{12}
}

func (x *StaffReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StaffReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *StaffReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StaffReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CName       string `protobuf:"bytes,1,opt,name=cName,proto3" json:"cName,omitempty"`             // team中文名称
	EName       string `protobuf:"bytes,2,opt,name=eName,proto3" json:"eName,omitempty"`             // team英文名称
	PreTeamCode string `protobuf:"bytes,3,opt,name=preTeamCode,proto3" json:"preTeamCode,omitempty"` // team前置代码 - 用于成员工号生成
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTeamRequest) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *CreateTeamRequest) GetEName() string {
	if x != nil {
		return x.EName
	}
	return ""
}

func (x *CreateTeamRequest) GetPreTeamCode() string {
	if x != nil {
		return x.PreTeamCode
	}
	return ""
}

type CreateTeamReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exec bool `protobuf:"varint,1,opt,name=exec,proto3" json:"exec,omitempty"`
}

func (x *CreateTeamReply) Reset() {
	*x = CreateTeamReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTeamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamReply) ProtoMessage() {}

func (x *CreateTeamReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamReply.ProtoReflect.Descriptor instead.
func (*CreateTeamReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{14}
}

func (x *CreateTeamReply) GetExec() bool {
	if x != nil {
		return x.Exec
	}
	return false
}

type UpdateTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CName       string `protobuf:"bytes,2,opt,name=cName,proto3" json:"cName,omitempty"`
	EName       string `protobuf:"bytes,3,opt,name=eName,proto3" json:"eName,omitempty"`
	PreTeamCode string `protobuf:"bytes,4,opt,name=preTeamCode,proto3" json:"preTeamCode,omitempty"`
}

func (x *UpdateTeamRequest) Reset() {
	*x = UpdateTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamRequest) ProtoMessage() {}

func (x *UpdateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTeamRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTeamRequest) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *UpdateTeamRequest) GetEName() string {
	if x != nil {
		return x.EName
	}
	return ""
}

func (x *UpdateTeamRequest) GetPreTeamCode() string {
	if x != nil {
		return x.PreTeamCode
	}
	return ""
}

type UpdateTeamReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exec bool `protobuf:"varint,1,opt,name=exec,proto3" json:"exec,omitempty"`
}

func (x *UpdateTeamReply) Reset() {
	*x = UpdateTeamReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTeamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamReply) ProtoMessage() {}

func (x *UpdateTeamReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamReply.ProtoReflect.Descriptor instead.
func (*UpdateTeamReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateTeamReply) GetExec() bool {
	if x != nil {
		return x.Exec
	}
	return false
}

type DeleteTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteTeamRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTeamReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exec bool `protobuf:"varint,1,opt,name=exec,proto3" json:"exec,omitempty"`
}

func (x *DeleteTeamReply) Reset() {
	*x = DeleteTeamReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTeamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamReply) ProtoMessage() {}

func (x *DeleteTeamReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamReply.ProtoReflect.Descriptor instead.
func (*DeleteTeamReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteTeamReply) GetExec() bool {
	if x != nil {
		return x.Exec
	}
	return false
}

type ReadTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadTeamRequest) Reset() {
	*x = ReadTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTeamRequest) ProtoMessage() {}

func (x *ReadTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTeamRequest.ProtoReflect.Descriptor instead.
func (*ReadTeamRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{19}
}

func (x *ReadTeamRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadTeamReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team *TeamReply `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
}

func (x *ReadTeamReply) Reset() {
	*x = ReadTeamReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTeamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTeamReply) ProtoMessage() {}

func (x *ReadTeamReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTeamReply.ProtoReflect.Descriptor instead.
func (*ReadTeamReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{20}
}

func (x *ReadTeamReply) GetTeam() *TeamReply {
	if x != nil {
		return x.Team
	}
	return nil
}

type ListTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pn          int32  `protobuf:"varint,1,opt,name=pn,proto3" json:"pn,omitempty"`       // 选择页
	PSize       int32  `protobuf:"varint,2,opt,name=pSize,proto3" json:"pSize,omitempty"` // 选择页列表项数量
	CName       string `protobuf:"bytes,3,opt,name=cName,proto3" json:"cName,omitempty"`
	EName       string `protobuf:"bytes,4,opt,name=eName,proto3" json:"eName,omitempty"`
	PreTeamCode string `protobuf:"bytes,5,opt,name=preTeamCode,proto3" json:"preTeamCode,omitempty"`
}

func (x *ListTeamRequest) Reset() {
	*x = ListTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamRequest) ProtoMessage() {}

func (x *ListTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamRequest.ProtoReflect.Descriptor instead.
func (*ListTeamRequest) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{21}
}

func (x *ListTeamRequest) GetPn() int32 {
	if x != nil {
		return x.Pn
	}
	return 0
}

func (x *ListTeamRequest) GetPSize() int32 {
	if x != nil {
		return x.PSize
	}
	return 0
}

func (x *ListTeamRequest) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *ListTeamRequest) GetEName() string {
	if x != nil {
		return x.EName
	}
	return ""
}

func (x *ListTeamRequest) GetPreTeamCode() string {
	if x != nil {
		return x.PreTeamCode
	}
	return ""
}

type ListTeamReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32        `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data  []*TeamReply `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListTeamReply) Reset() {
	*x = ListTeamReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTeamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamReply) ProtoMessage() {}

func (x *ListTeamReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamReply.ProtoReflect.Descriptor instead.
func (*ListTeamReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{22}
}

func (x *ListTeamReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTeamReply) GetData() []*TeamReply {
	if x != nil {
		return x.Data
	}
	return nil
}

type TeamReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CName       string `protobuf:"bytes,2,opt,name=cName,proto3" json:"cName,omitempty"`
	EName       string `protobuf:"bytes,3,opt,name=eName,proto3" json:"eName,omitempty"`
	PreTeamCode string `protobuf:"bytes,4,opt,name=preTeamCode,proto3" json:"preTeamCode,omitempty"`
	CreatedAt   string `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt   string `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *TeamReply) Reset() {
	*x = TeamReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staff_v1_staff_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamReply) ProtoMessage() {}

func (x *TeamReply) ProtoReflect() protoreflect.Message {
	mi := &file_staff_v1_staff_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamReply.ProtoReflect.Descriptor instead.
func (*TeamReply) Descriptor() ([]byte, []int) {
	return file_staff_v1_staff_proto_rawDescGZIP(), []int{23}
}

func (x *TeamReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TeamReply) GetCName() string {
	if x != nil {
		return x.CName
	}
	return ""
}

func (x *TeamReply) GetEName() string {
	if x != nil {
		return x.EName
	}
	return ""
}

func (x *TeamReply) GetPreTeamCode() string {
	if x != nil {
		return x.PreTeamCode
	}
	return ""
}

func (x *TeamReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TeamReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_staff_v1_staff_proto protoreflect.FileDescriptor

var file_staff_v1_staff_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x26, 0xfa, 0x42, 0x23, 0x72, 0x21, 0x32, 0x1f, 0x5e, 0x30, 0x3f, 0x28,
	0x31, 0x33, 0x7c, 0x31, 0x34, 0x7c, 0x31, 0x35, 0x7c, 0x31, 0x37, 0x7c, 0x31, 0x38, 0x7c, 0x31,
	0x39, 0x29, 0x5b, 0x30, 0x2d, 0x39, 0x5d, 0x7b, 0x39, 0x7d, 0x24, 0x52, 0x06, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x01, 0x18, 0x04, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x65, 0x78, 0x65, 0x63, 0x22, 0x92, 0x01, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x41, 0x0a, 0x06, 0x6d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x29, 0xfa, 0x42, 0x26, 0x72,
	0x24, 0x32, 0x1f, 0x5e, 0x30, 0x3f, 0x28, 0x31, 0x33, 0x7c, 0x31, 0x34, 0x7c, 0x31, 0x35, 0x7c,
	0x31, 0x37, 0x7c, 0x31, 0x38, 0x7c, 0x31, 0x39, 0x29, 0x5b, 0x30, 0x2d, 0x39, 0x5d, 0x7b, 0x39,
	0x7d, 0x24, 0xd0, 0x01, 0x01, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xfa, 0x42, 0x09,
	0x72, 0x07, 0x10, 0x01, 0x18, 0x04, 0xd0, 0x01, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x26, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x65, 0x78, 0x65, 0x63, 0x22, 0x2d, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02,
	0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78,
	0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x65, 0x78, 0x65, 0x63, 0x22, 0x2b,
	0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x0e, 0x52,
	0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x22, 0x2f, 0x0a,
	0x14, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28,
	0x0a, 0x12, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x65, 0x78, 0x65, 0x63, 0x22, 0xd1, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x02, 0x70, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x1a, 0x04,
	0x28, 0x01, 0x40, 0x01, 0x52, 0x02, 0x70, 0x6e, 0x12, 0x1f, 0x0a, 0x05, 0x70, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x1a, 0x04, 0x28, 0x0a,
	0x40, 0x01, 0x52, 0x05, 0x70, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x29, 0xfa, 0x42, 0x26, 0x72, 0x24,
	0x32, 0x1f, 0x5e, 0x30, 0x3f, 0x28, 0x31, 0x33, 0x7c, 0x31, 0x34, 0x7c, 0x31, 0x35, 0x7c, 0x31,
	0x37, 0x7c, 0x31, 0x38, 0x7c, 0x31, 0x39, 0x29, 0x5b, 0x30, 0x2d, 0x39, 0x5d, 0x7b, 0x39, 0x7d,
	0x24, 0xd0, 0x01, 0x01, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xfa, 0x42, 0x09, 0x72,
	0x07, 0x10, 0x01, 0x18, 0x04, 0xd0, 0x01, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x54, 0x0a, 0x0e,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x84, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09,
	0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x01, 0x18, 0x20, 0x52, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x05, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x0c, 0xfa, 0x42, 0x09, 0x72, 0x07, 0x10, 0x01, 0x18, 0x40, 0xd0, 0x01, 0x01, 0x52, 0x05, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04,
	0x10, 0x01, 0x18, 0x04, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x25, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x65, 0x78, 0x65, 0x63, 0x22, 0xa4, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22,
	0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xfa, 0x42, 0x09, 0x72, 0x07, 0x10, 0x01, 0x18,
	0x20, 0xd0, 0x01, 0x01, 0x52, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xfa, 0x42, 0x09, 0x72,
	0x07, 0x10, 0x01, 0x18, 0x40, 0xd0, 0x01, 0x01, 0x52, 0x05, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x2e, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xfa, 0x42, 0x09, 0x72, 0x07, 0x10, 0x01, 0x18, 0x04, 0xd0,
	0x01, 0x01, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x25, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x65, 0x78, 0x65, 0x63, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x65, 0x78, 0x65, 0x63, 0x22, 0x2a, 0x0a, 0x0f, 0x52,
	0x65, 0x61, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22,
	0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x54,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x65, 0x61, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61,
	0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52,
	0x04, 0x74, 0x65, 0x61, 0x6d, 0x22, 0xc5, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x02, 0x70, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x1a, 0x04, 0x28, 0x01, 0x40, 0x01,
	0x52, 0x02, 0x70, 0x6e, 0x12, 0x1f, 0x0a, 0x05, 0x70, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x1a, 0x04, 0x28, 0x0a, 0x40, 0x01, 0x52, 0x05,
	0x70, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xfa, 0x42, 0x09, 0x72, 0x07, 0x10, 0x01, 0x18, 0x20, 0xd0,
	0x01, 0x01, 0x52, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xfa, 0x42, 0x09, 0x72, 0x07, 0x10,
	0x01, 0x18, 0x40, 0xd0, 0x01, 0x01, 0x52, 0x05, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a,
	0x0b, 0x70, 0x72, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x0c, 0xfa, 0x42, 0x09, 0x72, 0x07, 0x10, 0x01, 0x18, 0x04, 0xd0, 0x01, 0x01,
	0x52, 0x0b, 0x70, 0x72, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x52, 0x0a,
	0x0d, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0xa5, 0x01, 0x0a, 0x09, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x72, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x72, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xe1, 0x06, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x12, 0x4f, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x66, 0x66, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61,
	0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x55, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61,
	0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61,
	0x6d, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x4c, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x12,
	0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x1f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x46, 0x0a,
	0x08, 0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x46, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61,
	0x6d, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x17, 0x5a,
	0x15, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_staff_v1_staff_proto_rawDescOnce sync.Once
	file_staff_v1_staff_proto_rawDescData = file_staff_v1_staff_proto_rawDesc
)

func file_staff_v1_staff_proto_rawDescGZIP() []byte {
	file_staff_v1_staff_proto_rawDescOnce.Do(func() {
		file_staff_v1_staff_proto_rawDescData = protoimpl.X.CompressGZIP(file_staff_v1_staff_proto_rawDescData)
	})
	return file_staff_v1_staff_proto_rawDescData
}

var file_staff_v1_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_staff_v1_staff_proto_goTypes = []interface{}{
	(*CreateStaffRequest)(nil),   // 0: api.staff.v1.CreateStaffRequest
	(*CreateStaffReply)(nil),     // 1: api.staff.v1.CreateStaffReply
	(*UpdateStaffRequest)(nil),   // 2: api.staff.v1.UpdateStaffRequest
	(*UpdateStaffReply)(nil),     // 3: api.staff.v1.UpdateStaffReply
	(*DeleteStaffRequest)(nil),   // 4: api.staff.v1.DeleteStaffRequest
	(*DeleteStaffReply)(nil),     // 5: api.staff.v1.DeleteStaffReply
	(*ReadStaffRequest)(nil),     // 6: api.staff.v1.ReadStaffRequest
	(*ReadStaffReply)(nil),       // 7: api.staff.v1.ReadStaffReply
	(*RecoveryStaffRequest)(nil), // 8: api.staff.v1.RecoveryStaffRequest
	(*RecoveryStaffReply)(nil),   // 9: api.staff.v1.RecoveryStaffReply
	(*ListStaffRequest)(nil),     // 10: api.staff.v1.ListStaffRequest
	(*ListStaffReply)(nil),       // 11: api.staff.v1.ListStaffReply
	(*StaffReply)(nil),           // 12: api.staff.v1.StaffReply
	(*CreateTeamRequest)(nil),    // 13: api.staff.v1.CreateTeamRequest
	(*CreateTeamReply)(nil),      // 14: api.staff.v1.CreateTeamReply
	(*UpdateTeamRequest)(nil),    // 15: api.staff.v1.UpdateTeamRequest
	(*UpdateTeamReply)(nil),      // 16: api.staff.v1.UpdateTeamReply
	(*DeleteTeamRequest)(nil),    // 17: api.staff.v1.DeleteTeamRequest
	(*DeleteTeamReply)(nil),      // 18: api.staff.v1.DeleteTeamReply
	(*ReadTeamRequest)(nil),      // 19: api.staff.v1.ReadTeamRequest
	(*ReadTeamReply)(nil),        // 20: api.staff.v1.ReadTeamReply
	(*ListTeamRequest)(nil),      // 21: api.staff.v1.ListTeamRequest
	(*ListTeamReply)(nil),        // 22: api.staff.v1.ListTeamReply
	(*TeamReply)(nil),            // 23: api.staff.v1.TeamReply
}
var file_staff_v1_staff_proto_depIdxs = []int32{
	12, // 0: api.staff.v1.ReadStaffReply.staff:type_name -> api.staff.v1.StaffReply
	12, // 1: api.staff.v1.ListStaffReply.data:type_name -> api.staff.v1.StaffReply
	23, // 2: api.staff.v1.ReadTeamReply.team:type_name -> api.staff.v1.TeamReply
	23, // 3: api.staff.v1.ListTeamReply.data:type_name -> api.staff.v1.TeamReply
	0,  // 4: api.staff.v1.Staff.CreateStaff:input_type -> api.staff.v1.CreateStaffRequest
	2,  // 5: api.staff.v1.Staff.UpdateStaff:input_type -> api.staff.v1.UpdateStaffRequest
	4,  // 6: api.staff.v1.Staff.DeleteStaff:input_type -> api.staff.v1.DeleteStaffRequest
	6,  // 7: api.staff.v1.Staff.ReadStaff:input_type -> api.staff.v1.ReadStaffRequest
	8,  // 8: api.staff.v1.Staff.RecoveryStaff:input_type -> api.staff.v1.RecoveryStaffRequest
	10, // 9: api.staff.v1.Staff.ListStaff:input_type -> api.staff.v1.ListStaffRequest
	13, // 10: api.staff.v1.Staff.CreateTeam:input_type -> api.staff.v1.CreateTeamRequest
	15, // 11: api.staff.v1.Staff.UpdateTeam:input_type -> api.staff.v1.UpdateTeamRequest
	17, // 12: api.staff.v1.Staff.DeleteTeam:input_type -> api.staff.v1.DeleteTeamRequest
	19, // 13: api.staff.v1.Staff.ReadTeam:input_type -> api.staff.v1.ReadTeamRequest
	21, // 14: api.staff.v1.Staff.ListTeam:input_type -> api.staff.v1.ListTeamRequest
	1,  // 15: api.staff.v1.Staff.CreateStaff:output_type -> api.staff.v1.CreateStaffReply
	3,  // 16: api.staff.v1.Staff.UpdateStaff:output_type -> api.staff.v1.UpdateStaffReply
	5,  // 17: api.staff.v1.Staff.DeleteStaff:output_type -> api.staff.v1.DeleteStaffReply
	7,  // 18: api.staff.v1.Staff.ReadStaff:output_type -> api.staff.v1.ReadStaffReply
	9,  // 19: api.staff.v1.Staff.RecoveryStaff:output_type -> api.staff.v1.RecoveryStaffReply
	11, // 20: api.staff.v1.Staff.ListStaff:output_type -> api.staff.v1.ListStaffReply
	14, // 21: api.staff.v1.Staff.CreateTeam:output_type -> api.staff.v1.CreateTeamReply
	16, // 22: api.staff.v1.Staff.UpdateTeam:output_type -> api.staff.v1.UpdateTeamReply
	18, // 23: api.staff.v1.Staff.DeleteTeam:output_type -> api.staff.v1.DeleteTeamReply
	20, // 24: api.staff.v1.Staff.ReadTeam:output_type -> api.staff.v1.ReadTeamReply
	22, // 25: api.staff.v1.Staff.ListTeam:output_type -> api.staff.v1.ListTeamReply
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_staff_v1_staff_proto_init() }
func file_staff_v1_staff_proto_init() {
	if File_staff_v1_staff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_staff_v1_staff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStaffReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStaffReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStaffReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadStaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadStaffReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoveryStaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoveryStaffReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStaffReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTeamReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTeamReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTeamReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTeamReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTeamReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staff_v1_staff_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_staff_v1_staff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staff_v1_staff_proto_goTypes,
		DependencyIndexes: file_staff_v1_staff_proto_depIdxs,
		MessageInfos:      file_staff_v1_staff_proto_msgTypes,
	}.Build()
	File_staff_v1_staff_proto = out.File
	file_staff_v1_staff_proto_rawDesc = nil
	file_staff_v1_staff_proto_goTypes = nil
	file_staff_v1_staff_proto_depIdxs = nil
}
